config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

	get '/auth/:provider/callback', to: 'sessions#create'
	
	get '/grades/index', to: 'grades#index'

  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :students
  resources :grades
  resources :subjects
  resources :brackets


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bracket.rb
class Bracket < ApplicationRecord
	has_many :student
	has_many :subject
end

app/models/grade.rb
class Grade < ApplicationRecord
	belongs_to :subject
	belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :user
	belongs_to :bracket
	has_many :grade
end


# how do I create student controller? Conflicts with migration

app/models/subject.rb
class Subject < ApplicationRecord
	belongs_to :bracket
	has_many :grade
end

app/models/user.rb
class User < ApplicationRecord
	has_one :student

	class << self
	  def from_omniauth(auth_hash)
	    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
	    user.name = auth_hash['info']['name']
	    user.location = auth_hash['info']['location']
	    user.image_url = auth_hash['info']['image']
	    user.url = auth_hash['info']['urls']['Twitter']
	    user.save!
	    user
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  helper_method :current_user
end

app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController

	def index
		@subjects	= Subject.all
	end

	def completed
		render 'grades_completed'
	end

	def show
	end

	def create
		binding.pry
		# need to take from params information to create new grades!!!!
		grades = Grade.new(params)

		if grades.save
			#it saved
		else
			flash[:notice] = "Grades were not saved."
		end

	end


	def create_grade
		grade = Grade.new()

	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def create
	  begin
	    @user = User.from_omniauth(request.env['omniauth.auth'])
	    session[:user_id] = @user.id
	    flash[:success] = "Welcome, #{@user.name}!"
	  rescue
	    flash[:warning] = "There was an error while trying to authenticate you..."
  	end
  redirect_to root_path
	end

	def destroy
		if current_user
    session.delete(:user_id)
    flash[:success] = 'See you!'
  	end
  redirect_to root_path
	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def create_student
		student = Student.new(user_params)
	end

	private

	def user_params
		params.require(:student).permit ()
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/grades/grades_completed.html.erb
<div class="container-result">
	<div class="page-header">
		<h3>Submission complete. </h3>
		<h4>Here's an overview of your grades and performance:</h4>
	</div>

	<div class="row">
	  <div class="col-sm-6 col-md-6">
	    <div class="thumbnail">
	      <!-- <img src="..." alt="..."> -->
	      <div class="caption">
	        <h3>Grades Summary</h3>
	        <p>Finance: 1 </p>
	        <p>Orga: 2 </p>
	        <p>Your GPA: 1.5/5 </p>
	        <p>
	        	<a href="#" class="btn btn-primary" role="button">More Info</a> 
	        	<a href="/grades/index" class="btn btn-default" role="button">Edit</a>
	        </p>
	      </div>
	    </div>
	  </div>

    <div class="col-sm-6 col-md-6">
	    <div class="thumbnail">
	      <!-- <img src="..." alt="..."> -->
	      <div class="caption">
	        <h3>Performance</h3>
	        <p>Rank: #1 </p>
	        <p>Percentile: not enough data available yet. </p>
	        <p> Advised action: none. </p>
	        <p>
	        	<a href="#" class="btn btn-primary" role="button">More Info</a> 
	        </p>
	      </div>
	    </div> 
  	</div>

</div>

app/views/grades/index.html.erb
<div class="grades-container">

	<div class="page-header">
		<h1> Welcome <%=current_user.name %>, please enter your grades here.</h1>
	</div>
	<form action="/grades" method="POST">
		<div class="form-shrinker">
			<div class="row">

				<% @subjects.each do |subject| %>

					<div class="col-md-6">
						<div class="input-group">
							<span class="input-group-addon" id="basic-addon1"> <%= subject.name %> </span>
							<input type="text" class="form-control" placeholder="Enter grade here" name="<%= subject.name %>" >
						</div>
					</div>

				<% end %>

			</div>
		</div>

		<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">	

		<div class="submit-button">
			
			<input type="submit" class="btn btn-info">Submit</a></a>
				
		</div>


	</form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flaxy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  	<nav class="navbar navbar-default navbar-fixed-top">

  		<div class="container">

    	  <div class="navbar-header" >
      		 <%= link_to image_tag("argo.png", :class => "logo-header"), root_path %>
    	  </div>

    		<div id="navbar">

      		<% if current_user %>

            <div class = "facebook-pic">

              <div class="nav navbar-nav pull-right">  

                <a><%= image_tag current_user.image_url, alt: current_user.name, :class => "img-circle" %></a>

                <a><%= link_to 'Log Out', logout_path, method: :delete %></a>

              </div>

            </div>

          <% else %>

            <ul class="nav navbar-nav pull-right">

              <li><%= link_to image_tag("facebook-login.png", :class => "facebook-log"), '/auth/facebook' %></li>

            </ul>

          <% end %>
    		</div>
  		</div>
		</nav>

<%= yield %>
   
  </body>
</html>

app/views/pages/_welcome.html.erb
<div class="homepage-hero-module">
        <div class="video-container">
            <div class="filter"></div>
            <video autoplay loop class="fillWidth">
                <source src=<%=asset_path("busypeople/MP4/Busy-People.mp4") %> type="video/mp4" />
                <source src=<%=asset_path("busypeople/WEBM/Busy-People.webm") %> type="video/webm" />
            </video>

            <div class ="title-container">

                <img src=<%=asset_path("argo-white.png") %> type="image/png" class="video-logo" />
                <h3 class="video-subtitle"> Find out how good you really are. </h3>
                <h4 class="welcome-line">Authenticate via Facebook to get started.</h4>

						</div>  

        </div>     
</div>




<!-- why is this not side wide? -->

app/views/pages/index.html.erb
<% if current_user %>
  <div class="student-container">
    <div class="page-header">
      <h1>Your grades and ranking overview will go here</h1>
    </div>
    <div class="panel panel-default">

      <div class="panel-body">
        <ul>
          <li><strong>Name:</strong> <%= current_user.name %></li>
          <li><strong>Provider:</strong> <%= current_user.provider %></li>
          <li><strong>uID:</strong> <%= current_user.uid %></li>
          <li><strong>Location:</strong> <%= current_user.location %></li>
          <li><strong>Avatar URL:</strong> <%= current_user.image_url %></li>
          <li><strong>URL:</strong> <%= current_user.url %></li>
        </ul>
      </div>
    </div>

    <div class="progress">
  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
    profile 60% completed.
  </div>
</div>
  <%= link_to(grades_path) do %>
    <button type="button" class="btn btn-info btn-lg"> Add Grades </button>
  <% end %>
   


  </div>
<% else %>
  <%= render :partial => 'welcome' %> 
<% end %>